cc_test(
  name = "unit_tests",
  srcs = ["unit_tests.cpp"],
  deps = ["//src/shell_executor:shell_executor",
          "@googletest//:gtest_main"]
)

cc_test(
  name = "integration_tests",
  srcs = ["integration_tests.cpp"],
  deps = ["//src/shell_executor:shell_executor",
          "@googletest//:gtest_main"]
)
